name: CI

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Validate package
        uses: heyhusen/archlinux-package-action@main
        id: makepkg
        with:
          flags: '-si --noconfirm --skippgpcheck'
          namcap: false

      - name: upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: python27-switch
          path: ${{ steps.makepkg.outputs.pkgfile0 }}
