name: CI

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Makepkg Build and Check
        id: makepkg
        uses: knautilus/archlinux-package-action@main
        with:
          flags: '-si --noconfirm --skippgpcheck'

      - name: Print Package Files
        run: |
          echo "Successfully created the following package archive"
          echo "Package: ${{ steps.makepkg.outputs.pkgfile0 }}"

      - name: upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: python38-switch
          path: ${{ steps.makepkg.outputs.pkgfile0 }}
